### ISSUE TITLE
About how this works

### ISSUE THREAD

**Issue by pyj-pd** [NyaomiDEV/WinPlayer-Node#1]
Hello, I recently found out this project. I struggled using NodeRT to control media playback, and this project saved me a lot.

However, I have some questions about how `Player` instance works. When does `onUpdate` function get called?

**Comment by NyaomiDEV** [comment]
First of all, this project works on a best effort basis. Things may crash. If you're willing to deal with that in your application, then fine, come for a ride!

`onUpdate` is fired every time the media playback session gets updated by the reporting player (eg. track change, pause and play, seek events).

Whenever it is fired, you have to get the update via `Player.getUpdate()`.

**Comment by pyj-pd** [comment]
Thank you for the quick response. I appreciate your work on this project! Have a great day.
