### ISSUE TITLE
Type issue

### ISSUE THREAD

**Issue by pyj-pd** [NyaomiDEV/WinPlayer-Node#2]
Hi, I recently found some type issues for the project.

**Comment by NyaomiDEV** [comment]
It is strange that artData is undefined. It should contain ArtData at all times, then the data itself can be an empty buffer and type can be an empty array... did I miss something

**Comment by pyj-pd** [comment]
![image](https://github.com/NyaomiDEV/WinPlayer-Node/assets/123401626/ef1130ed-cba4-453a-b8ce-943917206ae3)

Code:
```ts
const onPlayerUpdate = async () => {
  const update = await player.getUpdate()

  let musicPlayerResponse: MusicPlayerResponse =
    update === null ? null : parseMusicPlayerUpdate(update)
  if (update) console.log(update.metadata.artData)

  sendToEveryone(musicPlayerResponse)
}
```

It happened when I played a song, and closed(right click tray icon) Spotify.

**Comment by NyaomiDEV** [comment]
Are you sure the update is still there? The entire update might very well be undefined at that stage.

**Comment by pyj-pd** [comment]
> Are you sure the update is still there? The entire update might very well be undefined at that stage.

Yes, I used if statement to check if update is valid and not undefined, and since I am using TypeScript I also checked hovering mouse over `update` that it is not undefined and has type of `Update`.

**Comment by pyj-pd** [comment]
![image](https://github.com/NyaomiDEV/WinPlayer-Node/assets/123401626/74355ad0-ae4f-4df7-96b3-927609f1e9f3)
`album` and `albumArtist` are being `undefined` as well.

**Comment by NyaomiDEV** [comment]
Album is expected of media players and this is originally targeted at media players. I cannot guarantee any compatibility with websites such as YouTube. I will make that nullable for type consistency, but it all might just crash.

**Comment by pyj-pd** [comment]
Thanks, I checked the commitment. Is it okay to close issue now?

**Comment by NyaomiDEV** [comment]
I do not plan on putting this on NPM.
