### ISSUE TITLE
Module not working/not found

### ISSUE THREAD

**Issue by Lonely-Foxxy** [NyaomiDEV/WinPlayer-Node#4]
Hello, I would try this module but it looks like index.node (index.js?) is missing (_*.node_ in gitignore).
Is it intentional? Because looks like main part of code is missing (like _getPlayerManager()_ or _getFriendlyNameFor()_)

**Comment by NyaomiDEV** [comment]
This module autogenerates `index.node` when you install it. If it doesn't do so, check that your package manager correctly added the package without errors.

You also need to have the Rust toolchain correctly set up, and you also need `@napi-rs/cli` as a global npm package.

**Comment by Lonely-Foxxy** [comment]
I'm sorry I don't know Rust, I was just trying to import this module in my node project.
It looks way more complicated than a simple npm install.
Maybe need more installation instructions/requires?

**Comment by Lonely-Foxxy** [comment]
I managed to install and build everything, 
now it looks working fine, I can get all of my spotify status !

**Comment by Lozarth** [comment]
> I managed to install and build everything, now it looks working fine, I can get all of my spotify status !

How do I build?
