### ISSUE TITLE
How do you install the package?

### ISSUE THREAD

**Issue by lolouthefox** [NyaomiDEV/WinPlayer-Node#5]
Hi, I don't see the winplayer-rs on npm? How do I install it?

**Comment by NyaomiDEV** [comment]
it's not there because i dont think its beneficial to put it there.

anyway, npm the package manager can install projects from github directly, refer to the manual

**Comment by lolouthefox** [comment]
> anyway, npm the package manager can install projects from github directly, refer to the manual

What manual 😭

**Comment by lolouthefox** [comment]
Currently getting `Unknown file extension ".node" for C:\Users\liamc\WebstormProjects\playback-api\node_modules\@innei\winplayer-rs\index.node`

**Comment by lolouthefox** [comment]
Bruh, it looks like .node isn't supported anymore...
